-- MySQL Script generated by MySQL Workbench
-- Tue May 28 19:08:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Aluno` (
                                              `RA` VARCHAR(10) NOT NULL,
                                              `nome__aluno` VARCHAR(45) NOT NULL,
                                              `turma` VARCHAR(15) NOT NULL,
                                              PRIMARY KEY (`RA`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Livros` (
                                               `id__Livros` INT NOT NULL,
                                               `nome__livro` VARCHAR(45) NOT NULL,
                                               `descricao` VARCHAR(200) NOT NULL,
                                               PRIMARY KEY (`id__Livros`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`emprestimo` (
                                                   `Livros__id__Livros` INT NOT NULL,
                                                   `Aluno__RA` VARCHAR(10) NOT NULL,
                                                   PRIMARY KEY (`Livros__id__Livros`, `Aluno__RA`),
                                                   INDEX `fk_emprestimo_Aluno1_idx` (`Aluno__RA` ASC) VISIBLE,
                                                   CONSTRAINT `fk_emprestimo_Livros`
                                                       FOREIGN KEY (`Livros__id__Livros`)
                                                           REFERENCES `biblioteca`.`Livros` (`id__Livros`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_emprestimo_Aluno1`
                                                       FOREIGN KEY (`Aluno__RA`)
                                                           REFERENCES `biblioteca`.`Aluno` (`RA`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
